import Head from 'next/head'
import { useState } from 'react';
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'
import {Form, Button} from 'react-bootstrap'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

function Hintform(){
  const [inputValue, setInputValue] = useState('');
  const [responseData, setResponseData] = useState('');

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  const handleButtonClick = () => {
    axios.get(`http://localhost:8080/api/v1/Hints/${inputValue}`)
      .then((response) => {
        setResponseData(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  return (
    <div className={styles.main}>
      <h1 className={styles.title}>Enter the Question Number</h1>
      <Form>
        <Form.Group className="mb-3">
          <Form.Control className={styles.card} placeholder="Leetcode Number" value={inputValue} onChange={handleInputChange} ></Form.Control>
          <Button className={styles.card} type="button" onClick={handleButtonClick}>Get Hint</Button>
        </Form.Group>
      </Form>
      {responseData && (
  <div className={styles.description}>
    <h2 className={styles.content}>Need a hint?:</h2>
    <p>Hint: {responseData.intuition}</p>
    <p>Leetcode Number: {responseData.leetcodeId}</p>
    <p>Question Title: {responseData.questionTitle}</p>
    <p>Question Link: {responseData.questionLink}</p>
  </div>
)}
    </div>
    
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>The Leetcode Hint Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className}`}>
          <Hintform />
      </main>

    </>
  )
}
